# Generated by Django 5.2.7 on 2025-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ameneties',
            name='icon',
            field=models.ImageField(upload_to='amenities'),
        ),
    ]
